package org.usfirst.frc.team2813.subsystems;



import org.usfirst.frc.team2813.robot.RobotMap;

import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 *
 */
public class IntakePivot extends PIDSubsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController intakePivotLeft = RobotMap.intakePivotintakePivotLeft;
    SpeedController intakePivotRight = RobotMap.intakePivotintakePivotRight;
    AnalogPotentiometer intakePotLeft = RobotMap.intakePivotintakePotLeft;
    AnalogPotentiometer intakePotRight = RobotMap.intakePivotintakePotRight;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    double leftIn = 1.0;
    double rightIn = -1.0;
    double leftOut = -1.0;
    double rightOut = 1.0;
    double intakeStop = 0; 
    
    double intakePotLeftval, intakePotRightval;
    double intakePotLeftPID, intakePotRightPID;
    
    		

    // Initialize your subsystem here
    public IntakePivot() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        super("IntakePivot", 1.0, 0.0, 0.0);
        setAbsoluteTolerance(0.2);
        getPIDController().setContinuous(false);
        LiveWindow.addActuator("IntakePivot", "PIDSubsystem Controller", getPIDController());
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID

        // Use these to get going:
        // setSetpoint() -  Sets where the PID controller should move the system
        //                  to
        // enable() - Enables the PID controller.
    }
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
        return intakePotLeft.get();
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
    }
    
   /* protected void usePIDOutput(double outPID1) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);
    	

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
        intakePivotLeft.pidWrite(outPID1);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
    }
    */
    
    protected void usePIDOutput(double outPID) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);
    	

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
    	
        intakePivotRight.pidWrite(outPID);
        intakePivotLeft.pidWrite(-outPID);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
    }
   
    
    public void pivotIn() {
		intakePivotLeft.set(leftIn);
		intakePivotRight.set(rightIn);
	}
	public void pivotOut() {
		intakePivotLeft.set(leftOut);
		intakePivotRight.set(rightOut);
		
	}
	public void pivotStop() {
		intakePivotLeft.set(intakeStop);
		intakePivotRight.set(intakeStop);
	}
	public void potValue(){
		intakePotLeftval = intakePotLeft.get();
		intakePotRightval = intakePotRight.get();
	}
	public void potPID(){
		intakePotLeftPID= intakePotLeft.pidGet();
		intakePotRightPID= intakePotRight.pidGet();
	}
		
}


