package org.usfirst.frc.team2813.robot;

import org.usfirst.frc.team2813.commands.ClawIn;
import org.usfirst.frc.team2813.commands.ClawOut;
import org.usfirst.frc.team2813.commands.ElevatorDropTote;
import org.usfirst.frc.team2813.commands.ElevatorIncDown;
import org.usfirst.frc.team2813.commands.ElevatorIncUp;
import org.usfirst.frc.team2813.commands.ElevatorJogDown;
import org.usfirst.frc.team2813.commands.ElevatorJogUp;
import org.usfirst.frc.team2813.commands.ElevatorOneTote;
import org.usfirst.frc.team2813.commands.ElevatorPickup;
import org.usfirst.frc.team2813.commands.ElevatorReset;
import org.usfirst.frc.team2813.commands.IntakeDropTote;
import org.usfirst.frc.team2813.commands.IntakeLongTote;
import org.usfirst.frc.team2813.commands.IntakeWideTote;
import org.usfirst.frc.team2813.commands.PickupRoutine;
import org.usfirst.frc.team2813.commands.RollerIn;
import org.usfirst.frc.team2813.commands.RollerOut;
import org.usfirst.frc.team2813.commands.RollerRotate;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */

public class OI {
	// // CREATING BUTTONS
	// One type of button is a joystick button which is any button on a
	// joystick.
	// You create one by telling it which joystick it's on and which button
	// number it is.
	// Joystick stick = new Joystick(port);
	// Button button = new JoystickButton(stick, buttonNumber);

	// There are a few additional built in buttons you can use. Additionally,
	// by subclassing Button you can create custom triggers and bind those to
	// commands the same as any other Button.

	// // TRIGGERING COMMANDS WITH BUTTONS
	// Once you have a button, it's trivial to bind it to a button in one of
	// three ways:

	// Start the command when the button is pressed and let it run the command
	// until it is finished as determined by it's isFinished method.
	// button.whenPressed(new ExampleCommand());

	// Run the command while the button is being held down and interrupt it once
	// the button is released.
	// button.whileHeld(new ExampleCommand());

	// Start the command when the button is released and let it run the command
	// until it is finished as determined by it's isFinished method.
	// button.whenReleased(new ExampleCommand());

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public Joystick driver1;
	public Joystick driver2;
	public Joystick operator;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	public OI() {
		SmartDashboard.putData("Elevator Up Incremental", new ElevatorIncUp());
		SmartDashboard.putData("Elevator Down Incremental",
				new ElevatorIncDown());

		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

		operator = new Joystick(2);

		driver2 = new Joystick(1);

		driver1 = new Joystick(0);
		
		new JoystickButton(driver1, 10).whenPressed(new PickupRoutine());
		new JoystickButton(driver1, 6).whileHeld(new ElevatorJogUp());
		new JoystickButton(driver1, 7).whileHeld(new ElevatorJogDown());
		new JoystickButton(driver1, 8).whenPressed(new ElevatorReset());
		new JoystickButton(operator, 3).whenPressed(new ClawIn());
		new JoystickButton(operator, 7).whenPressed(new ClawOut());
		new JoystickButton(operator, 4).whenPressed(new IntakeLongTote());
		new JoystickButton(operator, 8).whenPressed(new IntakeWideTote());
		new JoystickButton(operator, 6).whileHeld(new RollerIn());
		new JoystickButton(operator, 2).whileHeld(new RollerOut());
		new JoystickButton(operator, 10).whileHeld(new RollerRotate());
		new JoystickButton(operator, 11).whenPressed(new ElevatorIncUp());
		new JoystickButton(operator, 12).whenPressed(new IntakeDropTote());
		System.out.println("check 1");
		new JoystickButton(operator, 1).whenPressed(new ElevatorDropTote());
		System.out.println("check 2");
		new JoystickButton(operator, 5).whenPressed(new ElevatorPickup());
		new JoystickButton(operator, 9).whenPressed(new ElevatorOneTote());

		// SmartDashboard Buttons
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	}

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
	public Joystick getdriver1() {
		return driver1;

	}

	public Joystick getdriver2() {
		return driver2;
	}

	public Joystick getoperator() {
		return operator;
	}

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

}
